export enum DashboardEnum {
  CAN_NOT_INTERACT = 'KHÔNG TƯƠNG TÁC',
  GOOD_INTERACTION = 'TƯƠNG TÁC TỐT',
  HAVE_AN_APPOINTMENT = 'CUỘC HẸN',
  JOINED_PROJECT = 'DỰ ÁN ĐÃ THAM GIA',
  MADE_PURCHASE = 'MUA SẮM',
  NO_DEMAND = 'KHÔNG CÓ NHU CẦU',
  TRANSFER_ANOTHER_EMPLOYEE = 'CHUYỂN NHÂN VIÊN KHÁC'
}
